export const cities = [
    {
      city: "Delhi", 
      lat: "28.6600", 
      long: "77.2300", 
      country: "India",  
      state: "Delhi", 
    }, 
    {
      city: "Mumbai", 
      lat: "18.9667", 
      long: "72.8333", 
      country: "India",  
      state: "Mahārāshtra", 
    
    }, 
    {
      city: "Kolkāta", 
      lat: "22.5411", 
      long: "88.3378", 
      country: "India",  
      state: "West Bengal", 
      
    }, 
    {
      city: "Bangalore", 
      lat: "12.9699", 
      long: "77.5980", 
      country: "India",  
      state: "Karnātaka", 
     
    }, 
    {
      city: "Chennai", 
      lat: "13.0825", 
      long: "80.2750", 
      country: "India",  
      state: "Tamil Nādu", 
     
    }, 
    {
      city: "Hyderābād", 
      lat: "17.3667", 
      long: "78.4667", 
      country: "India",  
      state: "Telangana", 
     
    }, 
    {
      city: "Pune", 
      lat: "18.5196", 
      long: "73.8553", 
      country: "India",  
      state: "Mahārāshtra", 
      
    }, 
    {
      city: "Ahmedabad", 
      lat: "23.0300", 
      long: "72.5800", 
      country: "India",  
      state: "Gujarāt", 
      
    }, 
    {
      city: "Sūrat", 
      lat: "21.1700", 
      long: "72.8300", 
      country: "India",  
      state: "Gujarāt", 
      
    }, 
    {
      city: "Lucknow", 
      lat: "26.8470", 
      long: "80.9470", 
      country: "India",  
      state: "Uttar Pradesh", 
      
    }, 
    {
      city: "Jaipur", 
      lat: "26.9167", 
      long: "75.8667", 
      country: "India",  
      state: "Rājasthān", 
      
    }, 
    {
      city: "Cawnpore", 
      lat: "26.4725", 
      long: "80.3311", 
      country: "India",  
      state: "Uttar Pradesh", 
      
    }, 
    {
      city: "Mirzāpur", 
      lat: "25.1500", 
      long: "82.5800", 
      country: "India",  
      state: "Uttar Pradesh", 
      
    }, 
    {
      city: "Nāgpur", 
      lat: "21.1539", 
      long: "79.0831", 
      country: "India",  
      state: "Mahārāshtra", 
      
    }, 
    {
      city: "Ghāziābād", 
      lat: "28.6667", 
      long: "77.4167", 
      country: "India",  
      state: "Uttar Pradesh", 
      
    }, 
    {
      city: "Indore", 
      lat: "22.7206", 
      long: "75.8472", 
      country: "India",  
      state: "Madhya Pradesh", 
      
    }, 
    {
      city: "Vadodara", 
      lat: "22.3000", 
      long: "73.2000", 
      country: "India",  
      state: "Gujarāt", 
      
    }, 
    {
      city: "Vishakhapatnam", 
      lat: "17.7333", 
      long: "83.3167", 
      country: "India",  
      state: "Andhra Pradesh", 
      
    }, 
    {
      city: "Bhopal", 
      lat: "23.2500", 
      long: "77.4167", 
      country: "India",  
      state: "Madhya Pradesh", 
      
    }, 
    {
      city: "Chinchvad", 
      lat: "18.6278", 
      long: "73.8131", 
      country: "India",  
      state: "Mahārāshtra", 
      
    }, 
    {
      city: "Patna", 
      lat: "25.6100", 
      long: "85.1414", 
      country: "India",  
      state: "Bihār", 
      
    }, 
    {
      city: "Ludhiāna", 
      lat: "30.9083", 
      long: "75.8486", 
      country: "India",  
      state: "Punjab", 
      
    }, 
    {
      city: "Āgra", 
      lat: "27.1800", 
      long: "78.0200", 
      country: "India",  
      state: "Uttar Pradesh", 
      
    }, 
    {
      city: "Kalyān", 
      lat: "19.2502", 
      long: "73.1602", 
      country: "India",  
      state: "Mahārāshtra", 
      
      
    }, 
    {
      city: "Madurai", 
      lat: "9.9197", 
      long: "78.1194", 
      country: "India",  
      state: "Tamil Nādu", 
      
    }, 
    {
      city: "Jamshedpur", 
      lat: "22.8000", 
      long: "86.1833", 
      country: "India",  
      state: "Jharkhand", 
      
    }, 
    {
      city: "Nāsik", 
      lat: "20.0000", 
      long: "73.7833", 
      country: "India",  
      state: "Mahārāshtra", 
      
    }, 
    {
      city: "Farīdābād", 
      lat: "28.4333", 
      long: "77.3167", 
      country: "India",  
      state: "Haryāna", 
     
    }, 
    {
      city: "Aurangābād", 
      lat: "19.8800", 
      long: "75.3200", 
      country: "India",  
      state: "Mahārāshtra", 
      
    }, 
    {
      city: "Rājkot", 
      lat: "22.2969", 
      long: "70.7984", 
      country: "India",  
      state: "Gujarāt", 
      
    }, 
    {
      city: "Meerut", 
      lat: "28.9900", 
      long: "77.7000", 
      country: "India",  
      state: "Uttar Pradesh", 
      
    }, 
    {
      city: "Jabalpur", 
      lat: "23.1667", 
      long: "79.9333", 
      country: "India",  
      state: "Madhya Pradesh", 
      
    }, 
    {
      city: "Thāne", 
      lat: "19.1800", 
      long: "72.9633", 
      country: "India",  
      state: "Mahārāshtra", 
      
    }, 
    {
      city: "Dhanbād", 
      lat: "23.7928", 
      long: "86.4350", 
      country: "India",  
      state: "Jharkhand", 
      
    }, 
    {
      city: "Allahābād", 
      lat: "25.4550", 
      long: "81.8400", 
      country: "India",  
      state: "Uttar Pradesh", 
      
    }, 
    {
      city: "Vārānasi", 
      lat: "25.3189", 
      long: "83.0128", 
      country: "India",  
      state: "Uttar Pradesh", 
     
    }, 
    {
      city: "Srīnagar", 
      lat: "34.0911", 
      long: "74.8061", 
      country: "India",  
      state: "Jammu and Kashmīr", 
   
    }, 
    {
      city: "Amritsar", 
      lat: "31.6167", 
      long: "74.8500", 
      country: "India",  
      state: "Punjab", 
    
    }, 
    {
      city: "Alīgarh", 
      lat: "27.8800", 
      long: "78.0800", 
      country: "India",  
      state: "Uttar Pradesh", 
     
    }, 
    {
      city: "Bhiwandi", 
      lat: "19.3000", 
      long: "73.0667", 
      country: "India",  
      state: "Mahārāshtra", 
    
    }, 
    {
      city: "Gwalior", 
      lat: "26.2150", 
      long: "78.1931", 
      country: "India",  
      state: "Madhya Pradesh", 
  
    }, 
    {
      city: "Bhilai", 
      lat: "21.2167", 
      long: "81.4333", 
      country: "India",  
      state: "Chhattīsgarh", 
  
    }, 
    {
      city: "Hāora", 
      lat: "22.5900", 
      long: "88.3100", 
      country: "India",  
      state: "West Bengal", 
  
    }, 
    {
      city: "Rānchi", 
      lat: "23.3556", 
      long: "85.3347", 
      country: "India",  
      state: "Jharkhand", 
     
    }, 
    {
      city: "Bezwāda", 
      lat: "16.5167", 
      long: "80.6167", 
      country: "India",  
      state: "Andhra Pradesh", 
    
    }, 
    {
      city: "Chandīgarh", 
      lat: "30.7353", 
      long: "76.7911", 
      country: "India",  
      state: "Chandīgarh", 
  
    }, 
    {
      city: "Mysore", 
      lat: "12.3086", 
      long: "76.6531", 
      country: "India",  
      state: "Karnātaka", 
    
    }, 
    {
      city: "Raipur", 
      lat: "21.2379", 
      long: "81.6337", 
      country: "India",  
      state: "Chhattīsgarh", 
      
    }, 
    {
      city: "Kota", 
      lat: "25.1800", 
      long: "75.8300", 
      country: "India",  
      state: "Rājasthān", 
      
    }, 
    {
      city: "Bareilly", 
      lat: "28.3640", 
      long: "79.4150", 
      country: "India",  
      state: "Uttar Pradesh", 
     
    }, 
    {
      city: "Jodhpur", 
      lat: "26.2918", 
      long: "73.0168", 
      country: "India",  
      state: "Rājasthān", 
      
    }, 
    {
      city: "Coimbatore", 
      lat: "11.0000", 
      long: "76.9667", 
      country: "India",  
      state: "Tamil Nādu", 
      
    }, 
    {
      city: "Dispur", 
      lat: "26.1500", 
      long: "91.7700", 
      country: "India",  
      state: "Assam", 
      
    }, 
    {
      city: "Guwāhāti", 
      lat: "26.1667", 
      long: "91.7667", 
      country: "India",  
      state: "Assam", 
      
    }, 
    {
      city: "Solāpur", 
      lat: "17.6833", 
      long: "75.9167", 
      country: "India",  
      state: "Mahārāshtra", 
      
    }, 
    {
      city: "Trichinopoly", 
      lat: "10.8269", 
      long: "78.6928", 
      country: "India",  
      state: "Tamil Nādu", 
     
    }, 
    {
      city: "Hubli", 
      lat: "15.3600", 
      long: "75.1250", 
      country: "India",  
      state: "Karnātaka", 
      
    }, 
    {
      city: "Jalandhar", 
      lat: "31.3256", 
      long: "75.5792", 
      country: "India",  
      state: "Punjab", 
      
    }, 
    {
      city: "Bhubaneshwar", 
      lat: "20.2644", 
      long: "85.8281", 
      country: "India",  
      state: "Odisha", 
      
    }, 
    {
      city: "Bhayandar", 
      lat: "19.3000", 
      long: "72.8500", 
      country: "India",  
      state: "Mahārāshtra", 
      
    }, 
    {
      city: "Morādābād", 
      lat: "28.8418", 
      long: "78.7568", 
      country: "India",  
      state: "Uttar Pradesh", 
     
    }, 
    {
      city: "Kolhāpur", 
      lat: "16.7000", 
      long: "74.2333", 
      country: "India",  
      state: "Mahārāshtra", 
      
    }, 
    {
      city: "Thiruvananthapuram", 
      lat: "8.5000", 
      long: "76.8997", 
      country: "India",  
      state: "Kerala", 
      
    }, 
    {
      city: "Sahāranpur", 
      lat: "29.9640", 
      long: "77.5460", 
      country: "India",  
      state: "Uttar Pradesh", 
      
    }, 
    {
      city: "Warangal", 
      lat: "17.9756", 
      long: "79.6011", 
      country: "India",  
      state: "Telangana", 
      
    }, 
    {
      city: "Salem", 
      lat: "11.6500", 
      long: "78.1667", 
      country: "India",  
      state: "Tamil Nādu", 
      
    }, 
    {
      city: "Mālegaon", 
      lat: "20.5500", 
      long: "74.5500", 
      country: "India",  
      state: "Mahārāshtra", 
      
    }, 
    {
      city: "Kochi", 
      lat: "9.9667", 
      long: "76.2833", 
      country: "India",  
      state: "Kerala", 
     
    }, 
    {
      city: "Gorakhpur", 
      lat: "26.7611", 
      long: "83.3667", 
      country: "India",  
      state: "Uttar Pradesh", 
      
    }, 
    {
      city: "Shimoga", 
      lat: "13.9304", 
      long: "75.5600", 
      country: "India",  
      state: "Karnātaka", 
      
    }, 
    {
      city: "Tiruppūr", 
      lat: "11.1075", 
      long: "77.3398", 
      country: "India",  
      state: "Tamil Nādu", 
      
    }, 
    {
      city: "Guntūr", 
      lat: "16.3000", 
      long: "80.4500", 
      country: "India",  
      state: "Andhra Pradesh", 
      
    }, 
    {
      city: "Raurkela", 
      lat: "22.2492", 
      long: "84.8828", 
      country: "India",  
      state: "Odisha", 
     
    }, 
    {
      city: "Mangalore", 
      lat: "12.8703", 
      long: "74.8806", 
      country: "India",  
      state: "Karnātaka"
    }, 
    {
      city: "Nānded", 
      lat: "19.1500", 
      long: "77.3333", 
      country: "India",  
      state: "Mahārāshtra", 
    }, 
    {
      city: "Cuttack", 
      lat: "20.4500", 
      long: "85.8667", 
      country: "India",  
      state: "Odisha", 
    }, 
    {
      city: "Chānda", 
      lat: "19.9500", 
      long: "79.3000", 
      country: "India",  
      state: "Mahārāshtra", 
    }, 
    {
      city: "Dehra Dūn", 
      lat: "30.3180", 
      long: "78.0290", 
      country: "India",  
      state: "Uttarakhand", 
    }, 
    {
      city: "Durgāpur", 
      lat: "23.5500", 
      long: "87.3200", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Āsansol", 
      lat: "23.6833", 
      long: "86.9667", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Bhāvnagar", 
      lat: "21.7650", 
      long: "72.1369", 
      country: "India",  
      state: "Gujarāt", 
    }, 
    {
      city: "Amrāvati", 
      lat: "20.9333", 
      long: "77.7500", 
      country: "India",  
      state: "Mahārāshtra", 
    }, 
    {
      city: "Nellore", 
      lat: "14.4333", 
      long: "79.9667", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Ajmer", 
      lat: "26.4680", 
      long: "74.6390", 
      country: "India",  
      state: "Rājasthān", 
    }, 
    {
      city: "Tinnevelly", 
      lat: "8.7289", 
      long: "77.7081", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Bīkaner", 
      lat: "28.0181", 
      long: "73.3169", 
      country: "India",  
      state: "Rājasthān", 
    }, 
    {
      city: "Agartala", 
      lat: "23.8333", 
      long: "91.2667", 
      country: "India",  
      state: "Tripura", 
    }, 
    {
      city: "Ujjain", 
      lat: "23.1828", 
      long: "75.7772", 
      country: "India",  
      state: "Madhya Pradesh", 
    }, 
    {
      city: "Jhānsi", 
      lat: "25.4486", 
      long: "78.5696", 
      country: "India",  
      state: "Uttar Pradesh", 
      
    }, 
    {
      city: "Ulhāsnagar", 
      lat: "19.2167", 
      long: "73.1500", 
      country: "India",  
      state: "Mahārāshtra", 
      
    }, 
    {
      city: "Davangere", 
      lat: "14.4667", 
      long: "75.9167", 
      country: "India",  
      state: "Karnātaka", 
    }, 
    {
      city: "Jammu", 
      lat: "32.7333", 
      long: "74.8500", 
      country: "India",  
      state: "Jammu and Kashmīr", 
    }, 
    {
      city: "Belgaum", 
      lat: "15.8667", 
      long: "74.5000", 
      country: "India",  
      state: "Karnātaka", 
    }, 
    {
      city: "Gulbarga", 
      lat: "17.3333", 
      long: "76.8333", 
      country: "India",  
      state: "Karnātaka", 
    }, 
    {
      city: "Jāmnagar", 
      lat: "22.4700", 
      long: "70.0700", 
      country: "India",  
      state: "Gujarāt", 
    }, 
    {
      city: "Dhūlia", 
      lat: "20.9000", 
      long: "74.7833", 
      country: "India",  
      state: "Mahārāshtra", 
    }, 
    {
      city: "Gaya", 
      lat: "24.7500", 
      long: "85.0167", 
      country: "India",  
      state: "Bihār", 
    }, 
    {
      city: "Jalgaon", 
      lat: "21.0167", 
      long: "75.5667", 
      country: "India",  
      state: "Mahārāshtra", 
    }, 
    {
      city: "Kurnool", 
      lat: "15.8222", 
      long: "78.0350", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Udaipur", 
      lat: "24.5833", 
      long: "73.6833", 
      country: "India",  
      state: "Rājasthān", 
    }, 
    {
      city: "Bellary", 
      lat: "15.1500", 
      long: "76.9150", 
      country: "India",  
      state: "Karnātaka", 
    }, 
    {
      city: "Sāngli", 
      lat: "16.8667", 
      long: "74.5667", 
      country: "India",  
      state: "Mahārāshtra", 
    }, 
    {
      city: "Tuticorin", 
      lat: "8.7833", 
      long: "78.1333", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Calicut", 
      lat: "11.2500", 
      long: "75.7667", 
      country: "India",  
      state: "Kerala", 
    }, 
    {
      city: "Akola", 
      lat: "20.7333", 
      long: "77.0000", 
      country: "India",  
      state: "Mahārāshtra", 
    }, 
    {
      city: "Bhāgalpur", 
      lat: "25.2500", 
      long: "87.0167", 
      country: "India",  
      state: "Bihār", 
    }, 
    {
      city: "Sīkar", 
      lat: "27.6119", 
      long: "75.1397", 
      country: "India",  
      state: "Rājasthān", 
    }, 
    {
      city: "Tumkūr", 
      lat: "13.3300", 
      long: "77.1000", 
      country: "India",  
      state: "Karnātaka", 
    }, 
    {
      city: "Quilon", 
      lat: "8.8853", 
      long: "76.5864", 
      country: "India",  
      state: "Kerala", 
    }, 
    {
      city: "Muzaffarnagar", 
      lat: "29.4708", 
      long: "77.7033", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Bhīlwāra", 
      lat: "25.3500", 
      long: "74.6333", 
      country: "India",  
      state: "Rājasthān", 
    }, 
    {
      city: "Nizāmābād", 
      lat: "18.6704", 
      long: "78.1000", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Bhātpāra", 
      lat: "22.8667", 
      long: "88.4167", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Kākināda", 
      lat: "16.9333", 
      long: "82.2167", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Parbhani", 
      lat: "19.2704", 
      long: "76.7600", 
      country: "India",  
      state: "Mahārāshtra", 
    }, 
    {
      city: "Pānihāti", 
      lat: "22.6900", 
      long: "88.3700", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Lātūr", 
      lat: "18.4004", 
      long: "76.5700", 
      country: "India",  
      state: "Mahārāshtra", 
    }, 
    {
      city: "Rohtak", 
      lat: "28.9000", 
      long: "76.5667", 
      country: "India",  
      state: "Haryāna", 
    }, 
    {
      city: "Rājapālaiyam", 
      lat: "9.4204", 
      long: "77.5800", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Ahmadnagar", 
      lat: "19.0833", 
      long: "74.7333", 
      country: "India",  
      state: "Mahārāshtra", 
    }, 
    {
      city: "Cuddapah", 
      lat: "14.4667", 
      long: "78.8167", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Rājahmundry", 
      lat: "16.9833", 
      long: "81.7833", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Alwar", 
      lat: "27.5667", 
      long: "76.6167", 
      country: "India",  
      state: "Rājasthān", 
    }, 
    {
      city: "Muzaffarpur", 
      lat: "26.1200", 
      long: "85.3833", 
      country: "India",  
      state: "Bihār", 
    }, 
    {
      city: "Bilāspur", 
      lat: "22.1500", 
      long: "82.0167", 
      country: "India",  
      state: "Chhattīsgarh", 
    }, 
    {
      city: "Mathura", 
      lat: "27.4833", 
      long: "77.6833", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Kāmārhāti", 
      lat: "22.6700", 
      long: "88.3700", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Patiāla", 
      lat: "30.3204", 
      long: "76.3850", 
      country: "India",  
      state: "Punjab", 
    }, 
    {
      city: "Saugor", 
      lat: "23.8504", 
      long: "78.7500", 
      country: "India",  
      state: "Madhya Pradesh", 
    }, 
    {
      city: "Bijāpur", 
      lat: "16.8244", 
      long: "75.7154", 
      country: "India",  
      state: "Karnātaka", 
    }, 
    {
      city: "Brahmapur", 
      lat: "19.3200", 
      long: "84.8000", 
      country: "India",  
      state: "Odisha", 
    }, 
    {
      city: "Shāhjānpur", 
      lat: "27.8804", 
      long: "79.9050", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Trichūr", 
      lat: "10.5200", 
      long: "76.2100", 
      country: "India",  
      state: "Kerala", 
    }, 
    {
      city: "Barddhamān", 
      lat: "23.2500", 
      long: "87.8500", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Kulti", 
      lat: "23.7300", 
      long: "86.8500", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Sambalpur", 
      lat: "21.4704", 
      long: "83.9701", 
      country: "India",  
      state: "Odisha", 
    }, 
    {
      city: "Purnea", 
      lat: "25.7800", 
      long: "87.4700", 
      country: "India",  
      state: "Bihār", 
    }, 
    {
      city: "Hisar", 
      lat: "29.1489", 
      long: "75.7367", 
      country: "India",  
      state: "Haryāna", 
    }, 
    {
      city: "Fīrozābād", 
      lat: "27.1500", 
      long: "78.3949", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Bīdar", 
      lat: "17.9229", 
      long: "77.5175", 
      country: "India",  
      state: "Karnātaka", 
    }, 
    {
      city: "Rāmpur", 
      lat: "28.8154", 
      long: "79.0250", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Shiliguri", 
      lat: "26.7200", 
      long: "88.4200", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Bāli", 
      lat: "22.6500", 
      long: "88.3400", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Pānīpat", 
      lat: "29.4004", 
      long: "76.9700", 
      country: "India",  
      state: "Haryāna", 
    }, 
    {
      city: "Karīmnagar", 
      lat: "18.4333", 
      long: "79.1500", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Bhuj", 
      lat: "23.2504", 
      long: "69.8100", 
      country: "India",  
      state: "Gujarāt", 
    }, 
    {
      city: "Ichalkaranji", 
      lat: "16.7000", 
      long: "74.4700", 
      country: "India",  
      state: "Mahārāshtra", 
    }, 
    {
      city: "Tirupati", 
      lat: "13.6500", 
      long: "79.4200", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Hospet", 
      lat: "15.2667", 
      long: "76.4000", 
      country: "India",  
      state: "Karnātaka", 
    }, 
    {
      city: "Āīzawl", 
      lat: "23.7104", 
      long: "92.7200", 
      country: "India",  
      state: "Mizoram", 
    }, 
    {
      city: "Sannai", 
      lat: "24.1600", 
      long: "80.8300", 
      country: "India",  
      state: "Madhya Pradesh", 
    }, 
    {
      city: "Bārāsat", 
      lat: "22.2333", 
      long: "88.4500", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Ratlām", 
      lat: "23.3167", 
      long: "75.0667", 
      country: "India",  
      state: "Madhya Pradesh", 
    }, 
    {
      city: "Handwāra", 
      lat: "34.4000", 
      long: "74.2800", 
      country: "India",  
      state: "Jammu and Kashmīr", 
    }, 
    {
      city: "Drug", 
      lat: "21.1900", 
      long: "81.2800", 
      country: "India",  
      state: "Chhattīsgarh", 
    }, 
    {
      city: "Imphāl", 
      lat: "24.8200", 
      long: "93.9500", 
      country: "India",  
      state: "Manipur", 
    }, 
    {
      city: "Anantapur", 
      lat: "14.6833", 
      long: "77.6000", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Etāwah", 
      lat: "26.7855", 
      long: "79.0150", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Rāichūr", 
      lat: "16.2104", 
      long: "77.3550", 
      country: "India",  
      state: "Karnātaka", 
    }, 
    {
      city: "Ongole", 
      lat: "15.5000", 
      long: "80.0500", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Bharatpur", 
      lat: "27.2172", 
      long: "77.4900", 
      country: "India",  
      state: "Rājasthān", 
    }, 
    {
      city: "Begusarai", 
      lat: "25.4200", 
      long: "86.1300", 
      country: "India",  
      state: "Bihār", 
    }, 
    {
      city: "Sonīpat", 
      lat: "28.9958", 
      long: "77.0114", 
      country: "India",  
      state: "Haryāna", 
    }, 
    {
      city: "Rāmgundam", 
      lat: "18.8000", 
      long: "79.4500", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Hāpur", 
      lat: "28.7437", 
      long: "77.7628", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Uluberiya", 
      lat: "22.4700", 
      long: "88.1100", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Porbandar", 
      lat: "21.6425", 
      long: "69.6047", 
      country: "India",  
      state: "Gujarāt", 
    }, 
    {
      city: "Pāli", 
      lat: "25.7725", 
      long: "73.3233", 
      country: "India",  
      state: "Rājasthān", 
    }, 
    {
      city: "Vizianagaram", 
      lat: "18.1167", 
      long: "83.4167", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Puducherry", 
      lat: "11.9300", 
      long: "79.8300", 
      country: "India",  
      state: "Puducherry", 
    }, 
    {
      city: "Karnāl", 
      lat: "29.6804", 
      long: "76.9700", 
      country: "India",  
      state: "Haryāna", 
    }, 
    {
      city: "Nāgercoil", 
      lat: "8.1700", 
      long: "77.4300", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Tanjore", 
      lat: "10.8000", 
      long: "79.1500", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Sambhal", 
      lat: "28.5800", 
      long: "78.5500", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Naihāti", 
      lat: "22.9000", 
      long: "88.4200", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Secunderābād", 
      lat: "17.4500", 
      long: "78.5000", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Kharagpur", 
      lat: "22.3302", 
      long: "87.3237", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Dindigul", 
      lat: "10.3500", 
      long: "77.9500", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Shimla", 
      lat: "31.1033", 
      long: "77.1722", 
      country: "India",  
      state: "Himāchal Pradesh", 
    }, 
    {
      city: "Ingrāj Bāzār", 
      lat: "25.0000", 
      long: "88.1500", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Ellore", 
      lat: "16.7000", 
      long: "81.1000", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Puri", 
      lat: "19.8000", 
      long: "85.8167", 
      country: "India",  
      state: "Odisha", 
    }, 
    {
      city: "Haldia", 
      lat: "22.0257", 
      long: "88.0583", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Nandyāl", 
      lat: "15.4800", 
      long: "78.4800", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Bulandshahr", 
      lat: "28.4104", 
      long: "77.8484", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Chakradharpur", 
      lat: "22.7000", 
      long: "85.6300", 
      country: "India",  
      state: "Jharkhand", 
    }, 
    {
      city: "Bhiwāni", 
      lat: "28.7833", 
      long: "76.1333", 
      country: "India",  
      state: "Haryāna", 
    }, 
    {
      city: "Gurgaon", 
      lat: "28.4500", 
      long: "77.0200", 
      country: "India",  
      state: "Haryāna", 
    }, 
    {
      city: "Burhānpur", 
      lat: "21.3004", 
      long: "76.1300", 
      country: "India",  
      state: "Madhya Pradesh", 
    }, 
    {
      city: "Khammam", 
      lat: "17.2500", 
      long: "80.1500", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Madhyamgram", 
      lat: "22.7000", 
      long: "88.4500", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Ghāndīnagar", 
      lat: "23.2200", 
      long: "72.6800", 
      country: "India",  
      state: "Gujarāt", 
    }, 
    {
      city: "Baharampur", 
      lat: "24.1000", 
      long: "88.2500", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Mahbūbnagar", 
      lat: "16.7333", 
      long: "77.9833", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Mahesāna", 
      lat: "23.6000", 
      long: "72.4000", 
      country: "India",  
      state: "Gujarāt", 
    }, 
    {
      city: "Ādoni", 
      lat: "15.6300", 
      long: "77.2800", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Rāiganj", 
      lat: "25.6167", 
      long: "88.1167", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Bhusāval", 
      lat: "21.0200", 
      long: "75.8300", 
      country: "India",  
      state: "Mahārāshtra", 
    }, 
    {
      city: "Bahraigh", 
      lat: "27.6204", 
      long: "81.6699", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Shrīrāmpur", 
      lat: "22.7500", 
      long: "88.3400", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Tonk", 
      lat: "26.1505", 
      long: "75.7900", 
      country: "India",  
      state: "Rājasthān", 
    }, 
    {
      city: "Sirsa", 
      lat: "29.4904", 
      long: "75.0300", 
      country: "India",  
      state: "Haryāna", 
    }, 
    {
      city: "Jaunpur", 
      lat: "25.7333", 
      long: "82.6833", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Madanapalle", 
      lat: "13.5500", 
      long: "78.5000", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Hugli", 
      lat: "22.9000", 
      long: "88.3900", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Vellore", 
      lat: "12.9204", 
      long: "79.1500", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Alleppey", 
      lat: "9.5004", 
      long: "76.3700", 
      country: "India",  
      state: "Kerala", 
    }, 
    {
      city: "Cuddalore", 
      lat: "11.7500", 
      long: "79.7500", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Deo", 
      lat: "24.6561", 
      long: "84.4356", 
      country: "India",  
      state: "Bihār", 
    }, 
    {
      city: "Chīrāla", 
      lat: "15.8200", 
      long: "80.3500", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Machilīpatnam", 
      lat: "16.1667", 
      long: "81.1333", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Medinīpur", 
      lat: "22.4333", 
      long: "87.3333", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Bāramūla", 
      lat: "34.2000", 
      long: "74.3400", 
      country: "India",  
      state: "Jammu and Kashmīr", 
    }, 
    {
      city: "Chandannagar", 
      lat: "22.8667", 
      long: "88.3833", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Fatehpur", 
      lat: "25.8804", 
      long: "80.8000", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Udipi", 
      lat: "13.3322", 
      long: "74.7461", 
      country: "India",  
      state: "Karnātaka", 
    }, 
    {
      city: "Tenāli", 
      lat: "16.2430", 
      long: "80.6400", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Sitalpur", 
      lat: "27.6300", 
      long: "80.7500", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Conjeeveram", 
      lat: "12.8308", 
      long: "79.7078", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Proddatūr", 
      lat: "14.7300", 
      long: "78.5500", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Navsāri", 
      lat: "20.8504", 
      long: "72.9200", 
      country: "India",  
      state: "Gujarāt", 
    }, 
    {
      city: "Godhra", 
      lat: "22.7755", 
      long: "73.6149", 
      country: "India",  
      state: "Gujarāt", 
    }, 
    {
      city: "Budaun", 
      lat: "28.0300", 
      long: "79.0900", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Chittoor", 
      lat: "13.2000", 
      long: "79.1167", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Harīpur", 
      lat: "31.5200", 
      long: "75.9800", 
      country: "India",  
      state: "Punjab", 
    }, 
    {
      city: "Saharsa", 
      lat: "25.8800", 
      long: "86.6000", 
      country: "India",  
      state: "Bihār", 
    }, 
    {
      city: "Vidisha", 
      lat: "23.5239", 
      long: "77.8061", 
      country: "India",  
      state: "Madhya Pradesh", 
    }, 
    {
      city: "Pathānkot", 
      lat: "32.2689", 
      long: "75.6497", 
      country: "India",  
      state: "Punjab", 
    }, 
    {
      city: "Nalgonda", 
      lat: "17.0500", 
      long: "79.2700", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Dibrugarh", 
      lat: "27.4833", 
      long: "95.0000", 
      country: "India",  
      state: "Assam", 
    }, 
    {
      city: "Bālurghāt", 
      lat: "25.2167", 
      long: "88.7667", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Krishnanagar", 
      lat: "23.4000", 
      long: "88.5000", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Fyzābād", 
      lat: "26.7504", 
      long: "82.1700", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Silchar", 
      lat: "24.7904", 
      long: "92.7900", 
      country: "India",  
      state: "Assam", 
    }, 
    {
      city: "Shāntipur", 
      lat: "23.2500", 
      long: "88.4300", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Hindupur", 
      lat: "13.8300", 
      long: "77.4900", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Erode", 
      lat: "11.3408", 
      long: "77.7172", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Jāmuria", 
      lat: "23.7000", 
      long: "87.0800", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Hābra", 
      lat: "22.8300", 
      long: "88.6300", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Ambāla", 
      lat: "30.3786", 
      long: "76.7725", 
      country: "India",  
      state: "Haryāna", 
    }, 
    {
      city: "Mauli", 
      lat: "30.7194", 
      long: "76.7181", 
      country: "India",  
      state: "Punjab", 
    }, 
    {
      city: "Kolār", 
      lat: "13.1333", 
      long: "78.1333", 
      country: "India",  
      state: "Karnātaka", 
    }, 
    {
      city: "Shillong", 
      lat: "25.5744", 
      long: "91.8789", 
      country: "India",  
      state: "Meghālaya", 
    }, 
    {
      city: "Bhīmavaram", 
      lat: "16.5333", 
      long: "81.5333", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "New Delhi", 
      lat: "28.7000", 
      long: "77.2000", 
      country: "India",  
      state: "Delhi", 
    }, 
    {
      city: "Mandsaur", 
      lat: "24.0300", 
      long: "75.0800", 
      country: "India",  
      state: "Madhya Pradesh", 
    }, 
    {
      city: "Kumbakonam", 
      lat: "10.9805", 
      long: "79.4000", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Tiruvannāmalai", 
      lat: "12.2604", 
      long: "79.1000", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Chicacole", 
      lat: "18.3000", 
      long: "83.9000", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Bānkura", 
      lat: "23.2500", 
      long: "87.0667", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Mandya", 
      lat: "12.5242", 
      long: "76.8958", 
      country: "India",  
      state: "Karnātaka", 
    }, 
    {
      city: "Hassan", 
      lat: "13.0050", 
      long: "76.1028", 
      country: "India",  
      state: "Karnātaka", 
    }, 
    {
      city: "Yavatmāl", 
      lat: "20.4000", 
      long: "78.1333", 
      country: "India",  
      state: "Mahārāshtra", 
    }, 
    {
      city: "Pīlibhīt", 
      lat: "28.6400", 
      long: "79.8100", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Pālghāt", 
      lat: "10.7792", 
      long: "76.6547", 
      country: "India",  
      state: "Kerala", 
    }, 
    {
      city: "Abohar", 
      lat: "30.1204", 
      long: "74.2900", 
      country: "India",  
      state: "Punjab", 
    }, 
    {
      city: "Pālakollu", 
      lat: "16.5333", 
      long: "81.7333", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Kānchrāpāra", 
      lat: "22.9700", 
      long: "88.4300", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Port Blair", 
      lat: "11.6667", 
      long: "92.7500", 
      country: "India",  
      state: "Andaman and Nicobar Islands", 
    }, 
    {
      city: "Alīpur Duār", 
      lat: "26.4837", 
      long: "89.5667", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Hāthras", 
      lat: "27.6000", 
      long: "78.0500", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Guntakal", 
      lat: "15.1700", 
      long: "77.3800", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Navadwīp", 
      lat: "23.4088", 
      long: "88.3657", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Basīrhat", 
      lat: "22.6572", 
      long: "88.8942", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Hālīsahar", 
      lat: "22.9500", 
      long: "88.4200", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Rishra", 
      lat: "22.7100", 
      long: "88.3500", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Dharmavaram", 
      lat: "14.4142", 
      long: "77.7150", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Baidyabāti", 
      lat: "22.7900", 
      long: "88.3200", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Darjeeling", 
      lat: "27.0417", 
      long: "88.2631", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Sopur", 
      lat: "34.3000", 
      long: "74.4700", 
      country: "India",  
      state: "Jammu and Kashmīr", 
    }, 
    {
      city: "Gudivāda", 
      lat: "16.4300", 
      long: "80.9900", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Adilābād", 
      lat: "19.6667", 
      long: "78.5333", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Titāgarh", 
      lat: "22.7400", 
      long: "88.3700", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Chittaurgarh", 
      lat: "24.8894", 
      long: "74.6239", 
      country: "India",  
      state: "Rājasthān", 
    }, 
    {
      city: "Narasaraopet", 
      lat: "16.2360", 
      long: "80.0540", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Dam Dam", 
      lat: "22.6200", 
      long: "88.4200", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Vālpārai", 
      lat: "10.3204", 
      long: "76.9700", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Osmānābād", 
      lat: "18.1667", 
      long: "76.0500", 
      country: "India",  
      state: "Mahārāshtra", 
    }, 
    {
      city: "Champdani", 
      lat: "22.8000", 
      long: "88.3700", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Bangaon", 
      lat: "23.0700", 
      long: "88.8200", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Khardah", 
      lat: "22.7200", 
      long: "88.3800", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Tādpatri", 
      lat: "14.9200", 
      long: "78.0200", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Jalpāiguri", 
      lat: "26.5167", 
      long: "88.7333", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Suriāpet", 
      lat: "17.1500", 
      long: "79.6167", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Tādepallegūdem", 
      lat: "16.8333", 
      long: "81.5000", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Bānsbāria", 
      lat: "22.9700", 
      long: "88.4000", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Negapatam", 
      lat: "10.7667", 
      long: "79.8333", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Bhadreswar", 
      lat: "22.8200", 
      long: "88.3500", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Chilakalūrupet", 
      lat: "16.0892", 
      long: "80.1672", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Kalyani", 
      lat: "22.9750", 
      long: "88.4344", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Gangtok", 
      lat: "27.3300", 
      long: "88.6200", 
      country: "India",  
      state: "Sikkim", 
    }, 
    {
      city: "Kohīma", 
      lat: "25.6667", 
      long: "94.1194", 
      country: "India",  
      state: "Nāgāland", 
    }, 
    {
      city: "Khambhāt", 
      lat: "22.3131", 
      long: "72.6194", 
      country: "India",  
      state: "Gujarāt", 
    }, 
    {
      city: "Aurangābād", 
      lat: "24.7704", 
      long: "84.3800", 
      country: "India",  
      state: "Bihār", 
    }, 
    {
      city: "Emmiganūr", 
      lat: "15.7333", 
      long: "77.4833", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Rāyachoti", 
      lat: "14.0500", 
      long: "78.7500", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Kāvali", 
      lat: "14.9123", 
      long: "79.9944", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Mancherāl", 
      lat: "18.8679", 
      long: "79.4639", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Kadiri", 
      lat: "14.1200", 
      long: "78.1700", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Ootacamund", 
      lat: "11.4086", 
      long: "76.6939", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Anakāpalle", 
      lat: "17.6800", 
      long: "83.0200", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Sirsilla", 
      lat: "18.3800", 
      long: "78.8300", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Kāmāreddipet", 
      lat: "18.3167", 
      long: "78.3500", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Pāloncha", 
      lat: "17.5815", 
      long: "80.6765", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Kottagūdem", 
      lat: "17.5500", 
      long: "80.6300", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Tanuku", 
      lat: "16.7500", 
      long: "81.7000", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Bodhan", 
      lat: "18.6700", 
      long: "77.9000", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Karūr", 
      lat: "10.9504", 
      long: "78.0833", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Mangalagiri", 
      lat: "16.4300", 
      long: "80.5500", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Kairāna", 
      lat: "29.4000", 
      long: "77.2000", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Mārkāpur", 
      lat: "15.7350", 
      long: "79.2700", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Malaut", 
      lat: "30.1900", 
      long: "74.4990", 
      country: "India",  
      state: "Punjab", 
    }, 
    {
      city: "Bāpatla", 
      lat: "15.8889", 
      long: "80.4700", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Badvel", 
      lat: "14.7500", 
      long: "79.0500", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Jorhāt", 
      lat: "26.7500", 
      long: "94.2167", 
      country: "India",  
      state: "Assam", 
    }, 
    {
      city: "Koratla", 
      lat: "18.8200", 
      long: "78.7200", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Pulivendla", 
      lat: "14.4167", 
      long: "78.2333", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Jaisalmer", 
      lat: "26.9167", 
      long: "70.9167", 
      country: "India",  
      state: "Rājasthān", 
    }, 
    {
      city: "Tādepalle", 
      lat: "16.4667", 
      long: "80.6000", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Armūr", 
      lat: "18.7900", 
      long: "78.2900", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Jatani", 
      lat: "20.1700", 
      long: "85.7000", 
      country: "India",  
      state: "Odisha", 
    }, 
    {
      city: "Gadwāl", 
      lat: "16.2300", 
      long: "77.8000", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Nagari", 
      lat: "13.3300", 
      long: "79.5800", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Wanparti", 
      lat: "16.3610", 
      long: "78.0627", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Ponnūru", 
      lat: "16.0667", 
      long: "80.5667", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Vinukonda", 
      lat: "16.0500", 
      long: "79.7500", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Itānagar", 
      lat: "27.1000", 
      long: "93.6200", 
      country: "India",  
      state: "Arunāchal Pradesh", 
    }, 
    {
      city: "Tezpur", 
      lat: "26.6338", 
      long: "92.8000", 
      country: "India",  
      state: "Assam", 
    }, 
    {
      city: "Narasapur", 
      lat: "16.4333", 
      long: "81.6833", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Kothāpet", 
      lat: "19.3333", 
      long: "79.4833", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Mācherla", 
      lat: "16.4800", 
      long: "79.4300", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Kandukūr", 
      lat: "15.2165", 
      long: "79.9042", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Sāmalkot", 
      lat: "17.0531", 
      long: "82.1695", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Bobbili", 
      lat: "18.5667", 
      long: "83.4167", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Sattenapalle", 
      lat: "16.3962", 
      long: "80.1497", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Vrindāvan", 
      lat: "27.5806", 
      long: "77.7006", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Mandapeta", 
      lat: "16.8700", 
      long: "81.9300", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Belampalli", 
      lat: "19.0558", 
      long: "79.4931", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Bhīmunipatnam", 
      lat: "17.8864", 
      long: "83.4471", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Nāndod", 
      lat: "21.8704", 
      long: "73.5026", 
      country: "India",  
      state: "Gujarāt", 
    }, 
    {
      city: "Pithāpuram", 
      lat: "17.1167", 
      long: "82.2667", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Punganūru", 
      lat: "13.3667", 
      long: "78.5833", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Puttūr", 
      lat: "13.4500", 
      long: "79.5500", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Jalor", 
      lat: "25.3500", 
      long: "72.6167", 
      country: "India",  
      state: "Rājasthān", 
    }, 
    {
      city: "Palmaner", 
      lat: "13.2000", 
      long: "78.7500", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Dholka", 
      lat: "22.7200", 
      long: "72.4700", 
      country: "India",  
      state: "Gujarāt", 
    }, 
    {
      city: "Jaggayyapeta", 
      lat: "16.8920", 
      long: "80.0976", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Tuni", 
      lat: "17.3500", 
      long: "82.5500", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Amalāpuram", 
      lat: "16.5833", 
      long: "82.0167", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Jagtiāl", 
      lat: "18.8000", 
      long: "78.9300", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Vikārābād", 
      lat: "17.3300", 
      long: "77.9000", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Venkatagiri", 
      lat: "13.9667", 
      long: "79.5833", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Sihor", 
      lat: "21.7000", 
      long: "71.9700", 
      country: "India",  
      state: "Gujarāt", 
    }, 
    {
      city: "Jangaon", 
      lat: "17.7200", 
      long: "79.1800", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Mandamāri", 
      lat: "18.9822", 
      long: "79.4811", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Metpalli", 
      lat: "18.8297", 
      long: "78.5878", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Repalle", 
      lat: "16.0200", 
      long: "80.8500", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Bhainsa", 
      lat: "19.1000", 
      long: "77.9667", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Jasdan", 
      lat: "22.0300", 
      long: "71.2000", 
      country: "India",  
      state: "Gujarāt", 
    }, 
    {
      city: "Jammalamadugu", 
      lat: "14.8500", 
      long: "78.3800", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Rāmeswaram", 
      lat: "9.2800", 
      long: "79.3000", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Addanki", 
      lat: "15.8110", 
      long: "79.9738", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Nidadavole", 
      lat: "16.9200", 
      long: "81.6700", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Bodupāl", 
      lat: "17.4139", 
      long: "78.5783", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Rājgīr", 
      lat: "25.0300", 
      long: "85.4200", 
      country: "India",  
      state: "Bihār", 
    }, 
    {
      city: "Rajaori", 
      lat: "33.3800", 
      long: "74.3000", 
      country: "India",  
      state: "Jammu and Kashmīr", 
    }, 
    {
      city: "Naini Tal", 
      lat: "29.3919", 
      long: "79.4542", 
      country: "India",  
      state: "Uttarakhand", 
    }, 
    {
      city: "Channarāyapatna", 
      lat: "12.9000", 
      long: "76.3900", 
      country: "India",  
      state: "Karnātaka", 
    }, 
    {
      city: "Maihar", 
      lat: "24.2700", 
      long: "80.7500", 
      country: "India",  
      state: "Madhya Pradesh", 
    }, 
    {
      city: "Panaji", 
      lat: "15.4800", 
      long: "73.8300", 
      country: "India",  
      state: "Goa", 
    }, 
    {
      city: "Junnar", 
      lat: "19.2000", 
      long: "73.8800", 
      country: "India",  
      state: "Mahārāshtra", 
    }, 
    {
      city: "Amudālavalasa", 
      lat: "18.4167", 
      long: "83.9000", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Damān", 
      lat: "20.4170", 
      long: "72.8500", 
      country: "India",  
      state: "Gujarāt", 
    }, 
    {
      city: "Kovvūr", 
      lat: "17.0167", 
      long: "81.7333", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Solan", 
      lat: "30.9200", 
      long: "77.1200", 
      country: "India",  
      state: "Himāchal Pradesh", 
    }, 
    {
      city: "Dwārka", 
      lat: "22.2403", 
      long: "68.9686", 
      country: "India",  
      state: "Gujarāt", 
    }, 
    {
      city: "Pathanāmthitta", 
      lat: "9.2647", 
      long: "76.7872", 
      country: "India",  
      state: "Kerala", 
    }, 
    {
      city: "Kodaikānal", 
      lat: "10.2300", 
      long: "77.4800", 
      country: "India",  
      state: "Tamil Nādu", 
    }, 
    {
      city: "Udhampur", 
      lat: "32.9300", 
      long: "75.1300", 
      country: "India",  
      state: "Jammu and Kashmīr", 
    }, 
    {
      city: "Giddalūr", 
      lat: "15.3784", 
      long: "78.9265", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Yellandu", 
      lat: "17.6000", 
      long: "80.3300", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Shrīrangapattana", 
      lat: "12.4181", 
      long: "76.6947", 
      country: "India",  
      state: "Karnātaka", 
    }, 
    {
      city: "Angamāli", 
      lat: "10.1960", 
      long: "76.3860", 
      country: "India",  
      state: "Kerala", 
    }, 
    {
      city: "Umaria", 
      lat: "23.5245", 
      long: "80.8365", 
      country: "India",  
      state: "Madhya Pradesh", 
    }, 
    {
      city: "Fatehpur Sīkri", 
      lat: "27.0911", 
      long: "77.6611", 
      country: "India",  
      state: "Uttar Pradesh", 
    }, 
    {
      city: "Mangūr", 
      lat: "17.9373", 
      long: "80.8185", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Pedana", 
      lat: "16.2667", 
      long: "81.1667", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Uran", 
      lat: "18.8900", 
      long: "72.9500", 
      country: "India",  
      state: "Mahārāshtra", 
    }, 
    {
      city: "Chimākurti", 
      lat: "15.5819", 
      long: "79.8680", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Devarkonda", 
      lat: "16.7000", 
      long: "78.9333", 
      country: "India",  
      state: "Telangana", 
    }, 
    {
      city: "Bandipura", 
      lat: "34.4225", 
      long: "74.6375", 
      country: "India",  
      state: "Jammu and Kashmīr", 
    }, 
    {
      city: "Silvassa", 
      lat: "20.2666", 
      long: "73.0166", 
      country: "India",  
      state: "Dādra and Nagar Haveli", 
    }, 
    {
      city: "Pāmidi", 
      lat: "14.9500", 
      long: "77.5833", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Narasannapeta", 
      lat: "18.4151", 
      long: "84.0447", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Jaynagar-Majilpur", 
      lat: "22.1772", 
      long: "88.4258", 
      country: "India",  
      state: "West Bengal", 
    }, 
    {
      city: "Khed Brahma", 
      lat: "24.0299", 
      long: "73.0463", 
      country: "India",  
      state: "Gujarāt", 
    }, 
    {
      city: "Khajurāho", 
      lat: "24.8500", 
      long: "79.9333", 
      country: "India",  
      state: "Madhya Pradesh", 
    }, 
    {
      city: "Koilkuntla", 
      lat: "15.2333", 
      long: "78.3167", 
      country: "India",  
      state: "Andhra Pradesh", 
    }, 
    {
      city: "Diu", 
      lat: "20.7197", 
      long: "70.9904", 
      country: "India",  
      state: "Damān and Diu", 
    }, 
    {
      city: "Kulgam", 
      lat: "33.6400", 
      long: "75.0200", 
      country: "India",  
      state: "Jammu and Kashmīr", 
    }, 
    {
      city: "Gauripur", 
      lat: "26.0800", 
      long: "89.9700", 
      country: "India",  
      state: "Assam", 
    }, 
    {
      city: "Abu", 
      lat: "24.5925", 
      long: "72.7083", 
      country: "India",  
      state: "Rājasthān", 
    }, 
    {
      city: "Curchorem", 
      lat: "15.2500", 
      long: "74.1000", 
      country: "India",  
      state: "Goa", 
    }, 
    {
      city: "Kavaratti", 
      lat: "10.5626", 
      long: "72.6369", 
      country: "India",  
      state: "Lakshadweep", 
    }, 
    {
      city: "Panchkula", 
      lat: "30.6915", 
      long: "76.8537", 
      country: "India",  
      state: "Haryāna", 
      
    }, 
    {
      city: "Kagaznāgār", 
      lat: "19.3316", 
      long: "79.4661", 
      country: "India",  
      state: "Telangana", 
      
    }
  ]